name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read          # pour checkout
  security-events: read   # üîë n√©cessaire pour CodeQL

jobs:

  devsecops:
    runs-on: ubuntu-latest

    steps:

    # 0Ô∏è‚É£ Checkout du repo
    - name: Checkout repository
      uses: actions/checkout@v3

    ############################################
    # 1Ô∏è‚É£ Analyse SAST avec CodeQL
    ############################################
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

    ############################################
    # 2Ô∏è‚É£ Analyse s√©curit√© Python avec Bandit
    ############################################
    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit
      run: bandit -r api --severity-level high

    ############################################
    # 3Ô∏è‚É£ Build Docker
    ############################################
    - name: Build Docker image
      run: docker build -t devsecops-api ./docker

    ############################################
    # 4Ô∏è‚É£ Scan Docker avec Trivy
    ############################################
    - name: Trivy Scan Docker Image
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: image
        image-ref: devsecops-api
        severity: CRITICAL,HIGH
        exit-code: 1
